In [5]:
import pandas as pd

In [6]:
training_file_path=r"E:\My new World\Ineuron\ML Projects\ml_housing_project\housing\artifact\data_ingestion\23-01-05-08-59-14\ingested_data\train\housing.csv"

df=pd.read_csv(training_file_path)

In [7]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   
3    -117.13     32.75                24.0       1877.0           519.0   
4    -118.70     34.28                27.0       3536.0           646.0   

   population  households  median_income  median_house_value ocean_proximity  
0      2237.0       706.0         2.1736             72100.0          INLAND  
1      2015.0       768.0         6.3373            279600.0      NEAR OCEAN  
2       667.0       300.0         2.8750             82700.0          INLAND  
3       898.0       483.0         2.2264            112500.0      NEAR OCEAN  
4      1837.0       580.0         4.4964            238300.0       <1H OCEAN

In [8]:
df.shape

(16512, 10)

In [9]:
df["median_house_value"]

0         72100.0
1        279600.0
2         82700.0
3        112500.0
4        238300.0
           ...   
16507    268500.0
16508     90400.0
16509    140400.0
16510    258100.0
16511     62700.0
Name: median_house_value, Length: 16512, dtype: float64

In [10]:
x,y=df.drop("median_house_value",axis=1),df[["median_house_value"]]

In [11]:
x.shape

(16512, 9)

In [12]:
y.shape

(16512, 1)

In [13]:
x.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [14]:
from sklearn.impute import SimpleImputer

In [15]:
numerical_column=x.drop(columns='ocean_proximity')
numerical_column

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -121.46     38.52                29.0       3873.0           797.0   
1        -117.23     33.09                 7.0       5320.0           855.0   
2        -119.04     35.37                44.0       1618.0           310.0   
3        -117.13     32.75                24.0       1877.0           519.0   
4        -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
16507    -117.07     33.03                14.0       6665.0          1231.0   
16508    -121.42     38.51                15.0       7901.0          1422.0   
16509    -122.72     38.44                48.0        707.0           166.0   
16510    -122.70     38.31                14.0       3155.0           580.0   
16511    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  
0          2237.0       706.0         2.1736  
1          2015.0       768.0         6.3373  
2           667.0       300.0         2.8750  
3           898.0       483.0         2.2264  
4          1837.0       580.0         4.4964  
...           ...         ...            ...  
16507      2026.0      1001.0         5.0900  
16508      4769.0      1418.0         2.8139  
16509       458.0       172.0         3.1797  
16510      1208.0       501.0         4.1964  
16511       625.0       197.0         3.1319  

[16512 rows x 8 columns]

In [16]:
simple_imputer=SimpleImputer(strategy='median')

In [17]:
simple_imputer.fit_transform(numerical_column)

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [18]:
df=simple_imputer.transform(numerical_column)

In [19]:
simple_imputer.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [20]:
simple_imputer.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [21]:
x.longitude.median()

-118.51

In [22]:
x.latitude.median()

34.26

In [23]:
x.ocean_proximity.value_counts()

<1H OCEAN     7277
INLAND        5262
NEAR OCEAN    2124
NEAR BAY      1847
ISLAND           2
Name: ocean_proximity, dtype: int64

In [24]:
simple_imputer=SimpleImputer(strategy="most_frequent")

In [25]:
from sklearn.base import BaseEstimator,TransformerMixin

In [26]:
import numpy as np

In [27]:
x.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity'],
      dtype='object')

In [28]:
COLUMN_TOTAL_ROOMS="total_rooms"
COLUMN_POPULATION="population"
COLUMN_HOUSEHOLDS="households"
COLUMN_TOTAL_BEDROOM="total_bedrooms"

class FeatureGenerator(BaseEstimator,TransformerMixin):
    def __init__(self,add_bedrooms_per_room=True,
                total_rooms_ix=3,
                population_ix=5,
                households_ix=6,
                total_bedrooms_ix=4, columns=None):
        """
        Feature Generator Initialization

        add_bedrooms_per_room: bool
        total_rooms_ix: int index number of toal rooms column
        population_ix: int index number of population column
        households_ix: int index number of household column
        total_bedrooms_ix: int index number of bedroom column
        
        
        """
        try:
            self.columns=columns
            if self.columns is not None:
                total_rooms_ix=self.columns.index(COLUMN_TOTAL_ROOMS)
                population_ix=self.columns.index(COLUMN_POPULATION)
                households_ix=self.columns.index(COLUMN_HOUSEHOLDS)
                total_bedrooms_ix=self.columns.index(COLUMN_TOTAL_BEDROOM)

            self.add_bedrooms_per_room=add_bedrooms_per_room
            self.total_rooms_ix=total_rooms_ix
            self.population_ix=population_ix
            self.households_ix=households_ix
            self.total_bedrooms_ix=total_bedrooms_ix

        except Exception as e:
            raise e

    def fit(self,x,y=None):
        return self

    def transform(self,x):
        try:
            room_per_household=x[:,self.total_rooms_ix]/x[:,self.households_ix]
            population_per_household=x[:,self.population_ix]/x[:,self.households_ix]
            if self.add_bedrooms_per_room:
                bedrooms_per_room=x[:,self.total_bedrooms_ix]/x[:,self.total_rooms_ix]
                generated_feature=np.c_[x,room_per_household,population_per_household,bedrooms_per_room]
            else:
                generated_feature=np.c_[x,room_per_household,population_per_household]

            return generated_feature
        except Exception as e:
            raise e


In [29]:
ar1=np.arange(2,10)
ar2=np.arange(12,20)

np.c_[ar1,ar2]

array([[ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

In [30]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

In [31]:
num_pipeline=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('feature_generator',FeatureGenerator()),
    ('scaling',StandardScaler())
])

In [32]:
from sklearn.preprocessing import OneHotEncoder

In [33]:
cat_pipeline=Pipeline([
    ('imputer',SimpleImputer(strategy="most_frequent")),
    ('OneHotEncoder',OneHotEncoder()),
    ('scaling',StandardScaler(with_mean=False))
])

In [34]:
x.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity'],
      dtype='object')

In [35]:
num_columns=['longitude', 'latitude', 'housing_median_age', 'total_rooms','total_bedrooms', 'population', 'households', 'median_income']
cat_columns=['ocean_proximity']

In [36]:
preprocessing=ColumnTransformer([
    ('num_pipeline',num_pipeline,num_columns),
    ('cat_pipeline',cat_pipeline,cat_columns)
]
)

In [37]:
df=pd.read_csv(training_file_path)

In [38]:
preprocessing.fit_transform(df)

array([[-0.94135046,  1.34743822,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.17178212, -1.19243966, -1.72201763, ...,  0.        ,
         0.        ,  2.9869105 ],
       [ 0.26758118, -0.1259716 ,  1.22045984, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ...,  0.        ,
         0.        ,  0.        ],
       [-1.56080303,  1.2492109 , -1.1653327 , ...,  0.        ,
         0.        ,  0.        ],
       [-1.28105026,  2.02567448, -0.13148926, ...,  0.        ,
         0.        ,  0.        ]])

In [39]:
test_df=r"E:\My new World\Ineuron\ML Projects\ml_housing_project\housing\artifact\data_ingestion\23-01-05-08-59-14\ingested_data\test\housing.csv"
preprocessing.fit_transform(pd.read_csv(test_df))

array([[ 0.57507019, -0.69657252,  0.0329564 , ...,  0.        ,
         0.        ,  0.        ],
       [-0.43480141, -0.33466769, -0.36298077, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.54522177, -0.63547171,  0.58726843, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.08656982, -0.54617051,  1.14158047, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.81385757, -0.92687559,  0.11214383, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.49049967, -0.66367208,  0.58726843, ...,  0.        ,
         0.        ,  0.        ]])

In [40]:
import dill

In [41]:
with open('preprocessing.pkl','wb') as prep_file:
    dill.dump(preprocessing,prep_file)

In [42]:
with open('preprocessing.pkl','rb') as file_obj:
    preprocessing_loaded_obj=dill.load(file_obj)

In [43]:
preprocessing_loaded_obj.transform(df)

array([[-0.95217406,  1.37145507,  0.0329564 , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.15213968, -1.18067898, -1.70916714, ...,  0.        ,
         0.        ,  2.97975134],
       [ 0.25171229, -0.10906468,  1.2207679 , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.57899091,  1.33385457,  1.53751764, ...,  0.        ,
         0.        ,  0.        ],
       [-1.56904144,  1.27275376, -1.15485511, ...,  0.        ,
         0.        ,  0.        ],
       [-1.29045617,  2.05296417, -0.12541847, ...,  0.        ,
         0.        ,  0.        ]])